### ISSUE TITLE
Login Component should be implemented

### ISSUE THREAD

**Issue by Ghislain1** [marco0237/Bibliotheksverwaltungssystem#32]
login

**Comment by marco0237** [comment]
- [Tkinter](https://docs.python.org/3/library/tkinter.html)
- SQL lite
- OOP
- Enkapselung in Python
- Design Patterm MVC
- Mathematische Operatoren in python z.b.: %-> Modulo, **-> Expo, //-> ganzeZahl
- Synthaxe Fehler für Code Qualität  in python ( pip3 install pylint, pip3 install pyflakes, pip3 install pep8)
